#!/bin/bash
set -e

echo "Installing Label Studio..."

# Detect the actual user (not root even when using sudo)
ACTUAL_USER="${SUDO_USER:-$USER}"
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)

echo "Detected user: $ACTUAL_USER"
echo "Home directory: $ACTUAL_HOME"

# Fix common apt repository issues before proceeding
echo "Checking apt repositories..."
if sudo apt-get update 2>&1 | grep -q "NO_PUBKEY\|not signed"; then
    echo "Warning: Some apt repositories have GPG key issues. These won't affect Label Studio installation."
    echo "Continuing with Label Studio setup..."
fi

# Check Python version (Label Studio requires >= 3.10)
PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "0.0")
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)
if [ "$PYTHON_MAJOR" -lt 3 ] || { [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 10 ]; }; then
    echo "Warning: Python $PYTHON_VERSION detected. Label Studio requires Python >= 3.10."
    echo "Attempting to install Python 3.12..."
    sudo apt-get install -y python3.12 python3.12-venv python3.12-dev || true
    # Use python3.12 if available
    if command -v python3.12 &>/dev/null; then
        PYTHON_BIN="python3.12"
    else
        echo "Warning: Could not install Python 3.12, continuing with $PYTHON_VERSION"
        PYTHON_BIN="python3"
    fi
else
    PYTHON_BIN="python3"
    echo "✓ Python $PYTHON_VERSION detected"
fi

# Install Python3 and pip if not already installed
echo "Installing Python dependencies..."
sudo apt-get install -y python3 python3-pip python3-venv || {
    echo "Error: Failed to install Python dependencies"
    exit 1
}

# Create a persistent directory for Label Studio in the user's home
LABEL_STUDIO_HOME="$ACTUAL_HOME/.label-studio"
echo "Creating Label Studio directory at: $LABEL_STUDIO_HOME"
sudo -u "$ACTUAL_USER" mkdir -p "$LABEL_STUDIO_HOME"

# Create a virtual environment for Label Studio
if [ ! -d "$LABEL_STUDIO_HOME/venv" ]; then
    echo "Creating Python virtual environment for Label Studio (using $PYTHON_BIN)..."
    sudo -u "$ACTUAL_USER" $PYTHON_BIN -m venv "$LABEL_STUDIO_HOME/venv" || {
        echo "Error: Failed to create virtual environment"
        exit 1
    }
fi

# Activate the virtual environment and install Label Studio
echo "Installing Label Studio in virtual environment..."
sudo -u "$ACTUAL_USER" bash << EOFVENV
source "$LABEL_STUDIO_HOME/venv/bin/activate"
pip install --upgrade pip
pip install label-studio
EOFVENV

# Verify installation
if [ ! -f "$LABEL_STUDIO_HOME/venv/bin/label-studio" ]; then
    echo "Error: Label Studio installation failed"
    exit 1
fi
echo "✓ Label Studio installed successfully"

# Get and display the installed version
LS_VERSION=$(sudo -u "$ACTUAL_USER" bash -c "source '$LABEL_STUDIO_HOME/venv/bin/activate' && label-studio --version 2>/dev/null" | grep -oP '\d+\.\d+\.\d+' || echo "unknown")
echo "✓ Label Studio version: $LS_VERSION"

# Write environment config file for Cloud Workstation proxy compatibility
echo "Writing environment config..."

# Generate a persistent SECRET_KEY if not already set
SECRET_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9!@#$%^&*' | head -c 50)

# Try to detect the Cloud Workstation hostname from the metadata server
WORKSTATION_URL=""
WORKSTATION_NAME=$(curl -s -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/hostname 2>/dev/null | cut -d. -f1 || echo "")
if [ -n "$WORKSTATION_NAME" ]; then
    # Typical Cloud Workstation port URL format
    WORKSTATION_URL="https://8080-${WORKSTATION_NAME}.cluster-$(curl -s -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/zone 2>/dev/null | grep -oP '[^/]+$' || echo 'unknown').cloudworkstations.dev"
    echo "Detected Cloud Workstation URL: $WORKSTATION_URL"
fi

sudo -u "$ACTUAL_USER" bash -c "cat > '$LABEL_STUDIO_HOME/.env'" << ENVEOF
# Label Studio environment configuration
# Generated by install_label_studio.sh on $(date)

# Persistent secret key (do not change after first run - will invalidate sessions)
SECRET_KEY=$SECRET_KEY

# Cloud Workstation proxy compatibility:
# Allows CSRF-protected login through Cloud Workstation port forwarding proxy
CSRF_TRUSTED_ORIGINS=https://*.cloudworkstations.dev,https://*.cluster-*.cloudworkstations.dev

# Trust the proxy's forwarded host header for correct URL generation
USE_X_FORWARDED_HOST=true

# Enable local file access for importing data from the workstation filesystem
LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true

# Restrict local file access to the data directory only (security best practice)
LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=$LABEL_STUDIO_HOME/data

# Reduce log verbosity (set to DEBUG for troubleshooting)
LABEL_STUDIO_LOG_LEVEL=WARNING
ENVEOF
echo "✓ Environment config written to $LABEL_STUDIO_HOME/.env"
echo "Creating startup script..."
STARTUP_SCRIPT="/etc/workstation-startup.d/50-start-label-studio"
sudo bash -c "cat > $STARTUP_SCRIPT" << 'EOF'
#!/bin/bash
# Start Label Studio on workstation boot

# Detect the actual user
ACTUAL_USER="${SUDO_USER:-$USER}"
if [ "$ACTUAL_USER" = "root" ]; then
    # Find the first non-root user with a home directory
    ACTUAL_USER=$(awk -F: '$3>=1000 && $3<60000 && $1!="nobody" {print $1; exit}' /etc/passwd)
fi
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)

LABEL_STUDIO_HOME="$ACTUAL_HOME/.label-studio"
LOG_FILE="$LABEL_STUDIO_HOME/label-studio.log"
ENV_FILE="$LABEL_STUDIO_HOME/.env"

# Ensure the directory exists
mkdir -p "$LABEL_STUDIO_HOME"
mkdir -p "$LABEL_STUDIO_HOME/data"

# Check if Label Studio is already running
if pgrep -f "label-studio start" > /dev/null; then
    echo "Label Studio is already running."
    exit 0
fi

# Start Label Studio as a background service
echo "Starting Label Studio..." | tee -a "$LOG_FILE"
cd "$LABEL_STUDIO_HOME"

# Source the .env file and run Label Studio as the actual user
su - "$ACTUAL_USER" -c "
    cd '$LABEL_STUDIO_HOME'
    # Load environment config if it exists
    if [ -f '$ENV_FILE' ]; then
        set -a
        source '$ENV_FILE'
        set +a
    fi
    nohup '$LABEL_STUDIO_HOME/venv/bin/label-studio' start \
        --host 0.0.0.0 \
        --port 8080 \
        --data-dir '$LABEL_STUDIO_HOME/data' \
        --no-browser \
        --log-level WARNING \
        >> '$LOG_FILE' 2>&1 &
    echo \$! > '$LABEL_STUDIO_HOME/label-studio.pid'
"

echo "Label Studio started. PID: $!" | tee -a "$LOG_FILE"
echo "Access at: http://localhost:8080" | tee -a "$LOG_FILE"
echo "Logs: $LOG_FILE"
EOF

# Make the startup script executable
sudo chmod +x "$STARTUP_SCRIPT"

# Create a convenient command to manage Label Studio
echo "Creating management commands..."
sudo bash -c 'cat > /usr/local/bin/label-studio-status' << 'EOF'
#!/bin/bash
ACTUAL_USER="${SUDO_USER:-$USER}"
if [ "$ACTUAL_USER" = "root" ]; then
    ACTUAL_USER=$(awk -F: '$3>=1000 && $3<60000 && $1!="nobody" {print $1; exit}' /etc/passwd)
fi
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)
LABEL_STUDIO_HOME="$ACTUAL_HOME/.label-studio"

if pgrep -f "label-studio start" > /dev/null; then
    VERSION=$("$LABEL_STUDIO_HOME/venv/bin/label-studio" --version 2>/dev/null | grep -oP '\d+\.\d+\.\d+' || echo "unknown")
    echo "✓ Label Studio is running"
    echo "  PID:     $(pgrep -f 'label-studio start')"
    echo "  Version: $VERSION"
    echo "  URL:     http://localhost:8080"
    echo "  Logs:    $LABEL_STUDIO_HOME/label-studio.log"
else
    echo "✗ Label Studio is not running"
    echo "  Start with: label-studio-restart"
fi
EOF
sudo chmod +x /usr/local/bin/label-studio-status

sudo bash -c 'cat > /usr/local/bin/label-studio-restart' << 'EOF'
#!/bin/bash
echo "Stopping Label Studio..."
pkill -f "label-studio start" || true
sleep 3
echo "Starting Label Studio..."
/etc/workstation-startup.d/50-start-label-studio
echo "Waiting for Label Studio to be ready..."
for i in $(seq 1 18); do
    sleep 10
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null)
    if echo "$HTTP_CODE" | grep -q "200\|302"; then
        echo "✓ Label Studio is ready at http://localhost:8080"
        exit 0
    fi
    echo "  Still starting... ($((i * 10))s)"
done
echo "Label Studio is taking longer than expected. Check logs with: label-studio-logs"
EOF
sudo chmod +x /usr/local/bin/label-studio-restart

sudo bash -c 'cat > /usr/local/bin/label-studio-stop' << 'EOF'
#!/bin/bash
if pgrep -f "label-studio start" > /dev/null; then
    echo "Stopping Label Studio..."
    pkill -f "label-studio start"
    echo "✓ Label Studio stopped."
else
    echo "Label Studio is not running."
fi
EOF
sudo chmod +x /usr/local/bin/label-studio-stop

sudo bash -c 'cat > /usr/local/bin/label-studio-logs' << 'EOF'
#!/bin/bash
ACTUAL_USER="${SUDO_USER:-$USER}"
if [ "$ACTUAL_USER" = "root" ]; then
    ACTUAL_USER=$(awk -F: '$3>=1000 && $3<60000 && $1!="nobody" {print $1; exit}' /etc/passwd)
fi
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)
LOG_FILE="$ACTUAL_HOME/.label-studio/label-studio.log"

if [ -f "$LOG_FILE" ]; then
    echo "=== Label Studio Logs ($LOG_FILE) ==="
    tail -f "$LOG_FILE"
else
    echo "Log file not found at: $LOG_FILE"
    echo "Label Studio may still be starting for the first time."
fi
EOF
sudo chmod +x /usr/local/bin/label-studio-logs

sudo bash -c 'cat > /usr/local/bin/label-studio-update' << 'EOF'
#!/bin/bash
ACTUAL_USER="${SUDO_USER:-$USER}"
if [ "$ACTUAL_USER" = "root" ]; then
    ACTUAL_USER=$(awk -F: '$3>=1000 && $3<60000 && $1!="nobody" {print $1; exit}' /etc/passwd)
fi
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)
LABEL_STUDIO_HOME="$ACTUAL_HOME/.label-studio"

echo "Stopping Label Studio..."
pkill -f "label-studio start" || true
sleep 2

echo "Updating Label Studio..."
sudo -u "$ACTUAL_USER" bash -c "
    source '$LABEL_STUDIO_HOME/venv/bin/activate'
    pip install --upgrade label-studio
"

echo "Restarting Label Studio..."
/etc/workstation-startup.d/50-start-label-studio
echo "✓ Update complete. Check version with: label-studio-status"
EOF
sudo chmod +x /usr/local/bin/label-studio-update

echo ""
echo "✓ Label Studio installation complete!"
echo ""
echo "Label Studio has been installed and will auto-start on workstation boot."
echo "All data is stored in: $LABEL_STUDIO_HOME"
echo "Config file:          $LABEL_STUDIO_HOME/.env"
echo ""
echo "Available commands:"
echo "  label-studio-status   - Check if Label Studio is running"
echo "  label-studio-restart  - Restart Label Studio"
echo "  label-studio-stop     - Stop Label Studio"
echo "  label-studio-logs     - View Label Studio logs"
echo "  label-studio-update   - Update Label Studio to latest version"
echo ""
echo "Starting Label Studio now..."
/etc/workstation-startup.d/50-start-label-studio
echo ""
echo "Waiting for Label Studio to initialize..."
echo "Note: First run may take 2-3 minutes while the database is set up."
echo ""

# Wait for Label Studio to be ready (first run needs longer due to DB migrations)
MAX_WAIT=180
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null)
    if echo "$HTTP_CODE" | grep -q "200\|302"; then
        echo ""
        echo "✓ Label Studio is ready! ($WAITED seconds)"
        echo ""
        echo "Access Label Studio at: http://localhost:8080"
        echo "For Cloud Workstations, use your workstation's port 8080 URL."
        exit 0
    fi
    sleep 10
    WAITED=$((WAITED + 10))
    # Show log tail every 30 seconds to help debug
    if [ $((WAITED % 30)) -eq 0 ]; then
        LOG_FILE="$LABEL_STUDIO_HOME/label-studio.log"
        if [ -f "$LOG_FILE" ]; then
            echo "  --- Recent log output ---"
            tail -3 "$LOG_FILE"
            echo "  -------------------------"
        fi
    fi
    echo "  Still waiting... ($WAITED seconds)"
done

echo ""
echo "Label Studio is taking longer than expected to start."
echo ""
echo "Check the process:  ps aux | grep label-studio"
echo "Check status:       label-studio-status"
echo "Check logs:         label-studio-logs"
echo ""
echo "Once ready, access at: http://localhost:8080"
