#!/bin/bash
set -e

# =============================================================================
# Label Studio Installation Script for Google Cloud Workstations
# Version: 2.0.1 (2024-03-24)
# =============================================================================
# Changes in 2.0.1:
#   - Fixed: grep -oP replaced with sed (PCRE not available on minimal Ubuntu)
#   - Fixed: heredoc syntax for .env file writing
# Changes in 2.0.0:
#   - Commands persist across workstation restarts (~/.local/bin/)
#   - Auto-start via .bashrc fallback
#   - USE_ENFORCE_CSRF_CHECKS=0 to disable CSRF (Cloud Workstations use IAM)
#   - SECURE_PROXY_SSL_HEADER for proper HTTPS detection behind proxy
#   - Dynamic URL detection from DNS/resolv.conf
#   - New commands: label-studio-set-url, label-studio-diagnostics
# =============================================================================
SCRIPT_VERSION="2.0.1"

echo "=============================================="
echo "Label Studio Installer v${SCRIPT_VERSION}"
echo "=============================================="
echo ""

# Detect the actual user (not root even when using sudo)
ACTUAL_USER="${SUDO_USER:-$USER}"
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)

echo "Detected user: $ACTUAL_USER"
echo "Home directory: $ACTUAL_HOME"

# Fix common apt repository issues before proceeding
echo "Checking apt repositories..."
if sudo apt-get update 2>&1 | grep -q "NO_PUBKEY\|not signed"; then
    echo "Warning: Some apt repositories have GPG key issues. These won't affect Label Studio installation."
    echo "Continuing with Label Studio setup..."
fi

# Check Python version (Label Studio requires >= 3.10)
PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "0.0")
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)
if [ "$PYTHON_MAJOR" -lt 3 ] || { [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 10 ]; }; then
    echo "Warning: Python $PYTHON_VERSION detected. Label Studio requires Python >= 3.10."
    echo "Attempting to install Python 3.12..."
    sudo apt-get install -y python3.12 python3.12-venv python3.12-dev || true
    # Use python3.12 if available
    if command -v python3.12 &>/dev/null; then
        PYTHON_BIN="python3.12"
    else
        echo "Warning: Could not install Python 3.12, continuing with $PYTHON_VERSION"
        PYTHON_BIN="python3"
    fi
else
    PYTHON_BIN="python3"
    echo "✓ Python $PYTHON_VERSION detected"
fi

# Install Python3 and pip if not already installed
echo "Installing Python dependencies..."
sudo apt-get install -y python3 python3-pip python3-venv || {
    echo "Error: Failed to install Python dependencies"
    exit 1
}

# Create a persistent directory for Label Studio in the user's home
LABEL_STUDIO_HOME="$ACTUAL_HOME/.label-studio"
echo "Creating Label Studio directory at: $LABEL_STUDIO_HOME"
sudo -u "$ACTUAL_USER" mkdir -p "$LABEL_STUDIO_HOME"

# Create a virtual environment for Label Studio
if [ ! -d "$LABEL_STUDIO_HOME/venv" ]; then
    echo "Creating Python virtual environment for Label Studio (using $PYTHON_BIN)..."
    sudo -u "$ACTUAL_USER" $PYTHON_BIN -m venv "$LABEL_STUDIO_HOME/venv" || {
        echo "Error: Failed to create virtual environment"
        exit 1
    }
fi

# Activate the virtual environment and install Label Studio
echo "Installing Label Studio in virtual environment..."
sudo -u "$ACTUAL_USER" bash << EOFVENV
source "$LABEL_STUDIO_HOME/venv/bin/activate"
pip install --upgrade pip
pip install label-studio
EOFVENV

# Verify installation
if [ ! -f "$LABEL_STUDIO_HOME/venv/bin/label-studio" ]; then
    echo "Error: Label Studio installation failed"
    exit 1
fi
echo "✓ Label Studio installed successfully"

# Get and display the installed version
# Note: Use sed instead of grep -P since Cloud Workstations may not have PCRE support
LS_VERSION=$(sudo -u "$ACTUAL_USER" bash -c "source '$LABEL_STUDIO_HOME/venv/bin/activate' && label-studio --version 2>/dev/null" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p' | head -1)
if [ -z "$LS_VERSION" ]; then
    LS_VERSION="unknown"
fi
echo "✓ Label Studio version: $LS_VERSION"

# Write environment config file for Cloud Workstation proxy compatibility
echo "Writing environment config..."

cat > "$LABEL_STUDIO_HOME/.env" << ENVEOF
# Label Studio environment configuration
# Generated by install_label_studio.sh v${SCRIPT_VERSION} on $(date)
#
# NOTE: LABEL_STUDIO_HOST and CSRF_TRUSTED_ORIGINS are set dynamically
# at each boot by the startup script using the detected workstation URL.
# To override manually, run: label-studio-set-url https://YOUR-URL

# Disable CSRF enforcement for Cloud Workstation reverse proxy compatibility.
# This is the correct approach: Cloud Workstations uses Google IAM for access
# control, so CSRF protection is redundant. See Label Studio source:
# core.middleware.DisableCSRF + USE_ENFORCE_CSRF_CHECKS setting.
USE_ENFORCE_CSRF_CHECKS=0

# Trust the proxy's forwarded headers for correct URL/protocol detection
USE_X_FORWARDED_HOST=true
USE_X_FORWARDED_PORT=true

# Tell Django the request is HTTPS when proxy sends X-Forwarded-Proto: https
# Format: header_name,expected_value (Django's SECURE_PROXY_SSL_HEADER)
SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https

# Enable local file access for importing data from the workstation filesystem
LOCAL_FILES_SERVING_ENABLED=true

# Restrict local file access to the data directory only (security best practice)
LOCAL_FILES_DOCUMENT_ROOT=$LABEL_STUDIO_HOME/data

# Reduce log verbosity (set to DEBUG for troubleshooting)
LOG_LEVEL=WARNING
ENVEOF
chown "$ACTUAL_USER:$ACTUAL_USER" "$LABEL_STUDIO_HOME/.env"
echo "✓ Environment config written to $LABEL_STUDIO_HOME/.env"

# ============================================================
# PERSISTENCE SETUP
# ============================================================
# Cloud Workstations only persist the home directory (~/).
# We install everything to ~/.label-studio/ and ~/.local/bin/.
# A small bootstrap in /etc/workstation-startup.d/ calls our
# persisted startup script. We also add ~/.local/bin to PATH.
# ============================================================

# Create directories
LOCAL_BIN="$ACTUAL_HOME/.local/bin"
sudo -u "$ACTUAL_USER" mkdir -p "$LOCAL_BIN"

# Add ~/.local/bin to PATH if not already present
BASHRC="$ACTUAL_HOME/.bashrc"
if ! grep -q 'export PATH=.*\.local/bin' "$BASHRC" 2>/dev/null; then
    echo "Adding ~/.local/bin to PATH in .bashrc..."
    sudo -u "$ACTUAL_USER" bash -c "echo '' >> '$BASHRC'"
    sudo -u "$ACTUAL_USER" bash -c "echo '# Label Studio management commands' >> '$BASHRC'"
    sudo -u "$ACTUAL_USER" bash -c "echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> '$BASHRC'"
fi

# Also add auto-start check to .bashrc as a fallback
# (runs on first login if startup.d didn't run)
if ! grep -q 'label-studio-autostart' "$BASHRC" 2>/dev/null; then
    sudo -u "$ACTUAL_USER" bash -c "cat >> '$BASHRC'" << 'BASHRC_EOF'

# Auto-start Label Studio if not running (fallback for Cloud Workstation restarts)
if [ -f "$HOME/.label-studio/startup.sh" ] && ! pgrep -f "label-studio start" > /dev/null 2>&1; then
    echo "Starting Label Studio in background..."
    nohup "$HOME/.label-studio/startup.sh" > /dev/null 2>&1 &
fi
# label-studio-autostart marker
BASHRC_EOF
fi

echo "Creating startup script..."

# Create the PERSISTENT startup script in ~/.label-studio/
sudo -u "$ACTUAL_USER" bash -c "cat > '$LABEL_STUDIO_HOME/startup.sh'" << 'EOF'
#!/bin/bash
# Start Label Studio on workstation boot
# This script is stored in ~/.label-studio/ so it persists across restarts.

# Detect the actual user
ACTUAL_USER="${SUDO_USER:-$USER}"
if [ "$ACTUAL_USER" = "root" ]; then
    # Find the first non-root user with a home directory
    ACTUAL_USER=$(awk -F: '$3>=1000 && $3<60000 && $1!="nobody" {print $1; exit}' /etc/passwd)
fi
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)

LABEL_STUDIO_HOME="$ACTUAL_HOME/.label-studio"
LOG_FILE="$LABEL_STUDIO_HOME/label-studio.log"
ENV_FILE="$LABEL_STUDIO_HOME/.env"
RUNTIME_ENV_FILE="$LABEL_STUDIO_HOME/.env.runtime"

# Ensure the directory exists
mkdir -p "$LABEL_STUDIO_HOME"
mkdir -p "$LABEL_STUDIO_HOME/data"

# Check if Label Studio is already running
if pgrep -f "label-studio start" > /dev/null; then
    echo "Label Studio is already running."
    exit 0
fi

# --- Detect Cloud Workstation URL for LABEL_STUDIO_HOST ---
# This is re-detected on every boot since the workstation hostname can change.
WS_NAME=$(hostname 2>/dev/null | tr -d '\n' || echo "")
CLUSTER_DOMAIN=""

# Method 1: Check DNS search domains (/etc/resolv.conf).
# Cloud Workstations typically adds cluster-*.cloudworkstations.dev as a search domain.
if [ -f /etc/resolv.conf ]; then
    CLUSTER_DOMAIN=$(grep -E '^search|^domain' /etc/resolv.conf 2>/dev/null \
        | grep -oE '[a-z0-9-]+\.cloudworkstations\.dev' \
        | head -1 || echo "")
fi

# Method 2: Try GCP metadata server custom attributes
if [ -z "$CLUSTER_DOMAIN" ]; then
    for attr in cluster-hostname workstation-cluster-domain workstation-cluster; do
        ATTR_VAL=$(curl -sf -m 2 -H 'Metadata-Flavor: Google' \
            "http://metadata.google.internal/computeMetadata/v1/instance/attributes/$attr" \
            2>/dev/null || echo "")
        if echo "$ATTR_VAL" | grep -q 'cloudworkstations\.dev'; then
            CLUSTER_DOMAIN=$(echo "$ATTR_VAL" | grep -oE '[a-z0-9-]+\.cloudworkstations\.dev' | head -1)
            break
        fi
    done
fi

# Build the runtime config file (overrides static .env at startup)
if [ -n "$CLUSTER_DOMAIN" ] && [ -n "$WS_NAME" ]; then
    WS_URL="https://8080-${WS_NAME}.${CLUSTER_DOMAIN}"
    echo "Detected Cloud Workstation URL: $WS_URL" | tee -a "$LOG_FILE"
    cat > "$RUNTIME_ENV_FILE" << DYNEOF
# Auto-detected runtime config — regenerated on each boot.
# To set manually: label-studio-set-url https://YOUR-WORKSTATION-URL
LABEL_STUDIO_HOST=${WS_URL}
CSRF_TRUSTED_ORIGINS=${WS_URL},https://*.cloudworkstations.dev
DYNEOF
elif [ -f "$LABEL_STUDIO_HOME/.env.custom" ]; then
    # Prefer manually configured URL (set via label-studio-set-url)
    cp "$LABEL_STUDIO_HOME/.env.custom" "$RUNTIME_ENV_FILE"
    echo "Using manually configured URL from .env.custom" | tee -a "$LOG_FILE"
else
    # Fallback: use wildcard CSRF origins and let LABEL_STUDIO_HOST default
    cat > "$RUNTIME_ENV_FILE" << DYNEOF
# Auto-detected runtime config — URL not detected, using wildcard origins.
# Run 'label-studio-set-url https://YOUR-WORKSTATION-URL' to fix CSRF errors.
CSRF_TRUSTED_ORIGINS=https://*.cloudworkstations.dev
DYNEOF
    echo "Note: Could not auto-detect Cloud Workstation URL." | tee -a "$LOG_FILE"
    echo "      Run 'label-studio-set-url https://PORT-HOST.CLUSTER.cloudworkstations.dev' if login fails." | tee -a "$LOG_FILE"
fi
chown "$ACTUAL_USER" "$RUNTIME_ENV_FILE" 2>/dev/null || true

# Start Label Studio as a background service
echo "Starting Label Studio..." | tee -a "$LOG_FILE"
cd "$LABEL_STUDIO_HOME"

# Source static .env, then dynamic .env.runtime, then run Label Studio
su - "$ACTUAL_USER" -c "
    cd '$LABEL_STUDIO_HOME'
    # Load static environment config
    if [ -f '$ENV_FILE' ]; then
        set -a
        source '$ENV_FILE'
        set +a
    fi
    # Load dynamic runtime config (auto-detected URL overrides static .env)
    if [ -f '$RUNTIME_ENV_FILE' ]; then
        set -a
        source '$RUNTIME_ENV_FILE'
        set +a
    fi
    nohup '$LABEL_STUDIO_HOME/venv/bin/label-studio' start \
        --host 0.0.0.0 \
        --port 8080 \
        --data-dir '$LABEL_STUDIO_HOME/data' \
        --no-browser \
        --log-level WARNING \
        >> '$LOG_FILE' 2>&1 &
    echo \$! > '$LABEL_STUDIO_HOME/label-studio.pid'
"

echo "Label Studio started." | tee -a "$LOG_FILE"
echo "Access at: http://localhost:8080" | tee -a "$LOG_FILE"
echo "Logs: $LOG_FILE"
EOF

# Make the persistent startup script executable
chmod +x "$LABEL_STUDIO_HOME/startup.sh"
chown "$ACTUAL_USER:$ACTUAL_USER" "$LABEL_STUDIO_HOME/startup.sh"

# Create a bootstrap in /etc/workstation-startup.d/ that calls our persistent script
# (This will be lost on restart but gets recreated by the .bashrc fallback)
STARTUP_SCRIPT="/etc/workstation-startup.d/50-start-label-studio"
if [ -d "/etc/workstation-startup.d" ]; then
    sudo bash -c "cat > '$STARTUP_SCRIPT'" << BOOTSTRAP_EOF
#!/bin/bash
# Bootstrap: calls the persistent startup script in the user's home directory
ACTUAL_USER=\$(awk -F: '\$3>=1000 && \$3<60000 && \$1!="nobody" {print \$1; exit}' /etc/passwd)
ACTUAL_HOME=\$(eval echo ~\$ACTUAL_USER)
if [ -f "\$ACTUAL_HOME/.label-studio/startup.sh" ]; then
    "\$ACTUAL_HOME/.label-studio/startup.sh"
fi
BOOTSTRAP_EOF
    sudo chmod +x "$STARTUP_SCRIPT"
fi

# Create management commands in ~/.local/bin/ (persists across restarts)
echo "Creating management commands in ~/.local/bin/..."

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-status'" << 'EOF'
#!/bin/bash
LABEL_STUDIO_HOME="$HOME/.label-studio"

if pgrep -f "label-studio start" > /dev/null; then
    VERSION=$("$LABEL_STUDIO_HOME/venv/bin/label-studio" --version 2>/dev/null | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p' | head -1)
    [ -z "$VERSION" ] && VERSION="unknown"
    echo "✓ Label Studio is running"
    echo "  PID:     $(pgrep -f 'label-studio start')"
    echo "  Version: $VERSION"
    echo "  URL:     http://localhost:8080"
    echo "  Logs:    $LABEL_STUDIO_HOME/label-studio.log"
else
    echo "✗ Label Studio is not running"
    echo "  Start with: label-studio-restart"
fi
EOF
chmod +x "$LOCAL_BIN/label-studio-status"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-restart'" << 'EOF'
#!/bin/bash
LABEL_STUDIO_HOME="$HOME/.label-studio"

echo "Stopping Label Studio..."
pkill -f "label-studio start" || true
sleep 3
echo "Starting Label Studio..."
"$LABEL_STUDIO_HOME/startup.sh"
echo "Waiting for Label Studio to be ready..."
for i in $(seq 1 18); do
    sleep 10
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null)
    if echo "$HTTP_CODE" | grep -q "200\|302"; then
        echo "✓ Label Studio is ready at http://localhost:8080"
        exit 0
    fi
    echo "  Still starting... ($((i * 10))s)"
done
echo "Label Studio is taking longer than expected. Check logs with: label-studio-logs"
EOF
chmod +x "$LOCAL_BIN/label-studio-restart"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-stop'" << 'EOF'
#!/bin/bash
if pgrep -f "label-studio start" > /dev/null; then
    echo "Stopping Label Studio..."
    pkill -f "label-studio start"
    echo "✓ Label Studio stopped."
else
    echo "Label Studio is not running."
fi
EOF
chmod +x "$LOCAL_BIN/label-studio-stop"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-logs'" << 'EOF'
#!/bin/bash
LOG_FILE="$HOME/.label-studio/label-studio.log"

if [ -f "$LOG_FILE" ]; then
    echo "=== Label Studio Logs ($LOG_FILE) ==="
    tail -f "$LOG_FILE"
else
    echo "Log file not found at: $LOG_FILE"
    echo "Label Studio may still be starting for the first time."
fi
EOF
chmod +x "$LOCAL_BIN/label-studio-logs"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-update'" << 'EOF'
#!/bin/bash
LABEL_STUDIO_HOME="$HOME/.label-studio"

echo "Stopping Label Studio..."
pkill -f "label-studio start" || true
sleep 2

echo "Updating Label Studio..."
source "$LABEL_STUDIO_HOME/venv/bin/activate"
pip install --upgrade label-studio

echo "Restarting Label Studio..."
"$LABEL_STUDIO_HOME/startup.sh"
echo "✓ Update complete. Check version with: label-studio-status"
EOF
chmod +x "$LOCAL_BIN/label-studio-update"

# Set workstation URL for CSRF / proxy compatibility
sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-set-url'" << 'EOF'
#!/bin/bash
# Usage: label-studio-set-url https://8080-w-NAME.cluster-ID.cloudworkstations.dev
LABEL_STUDIO_HOME="$HOME/.label-studio"

if [ -z "$1" ]; then
    echo "Usage: label-studio-set-url https://PORT-HOST.CLUSTER.cloudworkstations.dev"
    echo ""
    echo "This sets the external URL Label Studio uses for CSRF and link generation."
    echo "Find your URL in the Cloud Workstations web console (port 8080 forwarding link)."
    echo ""
    if [ -f "$LABEL_STUDIO_HOME/.env.custom" ]; then
        echo "Current custom URL config:"
        cat "$LABEL_STUDIO_HOME/.env.custom"
    fi
    exit 1
fi

WS_URL="$1"
# Strip trailing slash
WS_URL="${WS_URL%/}"

if ! echo "$WS_URL" | grep -q '^https\?://'; then
    echo "Error: URL must start with http:// or https://"
    exit 1
fi

echo "Setting Label Studio external URL to: $WS_URL"
cat > "$LABEL_STUDIO_HOME/.env.custom" << CUSTOMEOF
# Manually configured Label Studio URL (set via label-studio-set-url)
# To update: label-studio-set-url https://YOUR-NEW-URL
LABEL_STUDIO_HOST=${WS_URL}
CSRF_TRUSTED_ORIGINS=${WS_URL},https://*.cloudworkstations.dev
CUSTOMEOF

echo "✓ URL saved to $LABEL_STUDIO_HOME/.env.custom"
echo "  Restarting Label Studio to apply..."
label-studio-restart
EOF
chmod +x "$LOCAL_BIN/label-studio-set-url"

# Write the installer version to a file so diagnostics can read it
echo "$SCRIPT_VERSION" > "$LABEL_STUDIO_HOME/.installer-version"
chown "$ACTUAL_USER:$ACTUAL_USER" "$LABEL_STUDIO_HOME/.installer-version"

# Diagnostics command for troubleshooting CSRF and proxy issues
sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-diagnostics'" << 'EOF'
#!/bin/bash
LABEL_STUDIO_HOME="$HOME/.label-studio"

echo "=== Label Studio Diagnostics ==="
echo ""

# Show versions
INSTALLER_VER="unknown"
if [ -f "$LABEL_STUDIO_HOME/.installer-version" ]; then
    INSTALLER_VER=$(cat "$LABEL_STUDIO_HOME/.installer-version")
fi
LS_VER=$("$LABEL_STUDIO_HOME/venv/bin/label-studio" --version 2>/dev/null | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p' | head -1)
[ -z "$LS_VER" ] && LS_VER="unknown"
echo "--- Versions ---"
echo "  Installer script: v${INSTALLER_VER}"
echo "  Label Studio:     v${LS_VER}"
echo ""

echo "--- Process ---"
if pgrep -f "label-studio start" > /dev/null; then
    echo "✓ Label Studio is RUNNING (PID: $(pgrep -f 'label-studio start'))"
else
    echo "✗ Label Studio is NOT running"
fi
echo ""
echo "--- HTTP Check ---"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null)
echo "  localhost:8080 response: HTTP $HTTP_CODE"
echo ""
echo "--- Static config ($LABEL_STUDIO_HOME/.env) ---"
if [ -f "$LABEL_STUDIO_HOME/.env" ]; then
    grep -v '^#' "$LABEL_STUDIO_HOME/.env" | grep -v '^$'
else
    echo "  (not found)"
fi
echo ""
echo "--- Runtime config ($LABEL_STUDIO_HOME/.env.runtime) ---"
if [ -f "$LABEL_STUDIO_HOME/.env.runtime" ]; then
    grep -v '^#' "$LABEL_STUDIO_HOME/.env.runtime" | grep -v '^$'
else
    echo "  (not found — startup script may not have run yet)"
fi
echo ""
echo "--- Custom URL config ($LABEL_STUDIO_HOME/.env.custom) ---"
if [ -f "$LABEL_STUDIO_HOME/.env.custom" ]; then
    grep -v '^#' "$LABEL_STUDIO_HOME/.env.custom" | grep -v '^$'
else
    echo "  (not set — run 'label-studio-set-url https://YOUR-URL' if CSRF errors occur)"
fi
echo ""
echo "--- Hostname / DNS ---"
echo "  hostname:    $(hostname 2>/dev/null)"
echo "  DNS search:  $(grep -E '^search|^domain' /etc/resolv.conf 2>/dev/null | head -1 || echo '(not found)')"
CW_DOMAIN=$(grep -E '^search|^domain' /etc/resolv.conf 2>/dev/null \
    | grep -oE '[a-z0-9-]+\.cloudworkstations\.dev' | head -1 || echo "")
if [ -n "$CW_DOMAIN" ]; then
    echo "  Cloud Workstation domain: $CW_DOMAIN"
    echo "  ✓ Expected URL: https://8080-$(hostname).${CW_DOMAIN}"
else
    echo "  ✗ Could not detect Cloud Workstation domain from DNS"
    echo "    Manual fix: label-studio-set-url https://PORT-HOST.CLUSTER.cloudworkstations.dev"
fi
echo ""
echo "--- Recent log (last 10 lines) ---"
LOG_FILE="$LABEL_STUDIO_HOME/label-studio.log"
if [ -f "$LOG_FILE" ]; then
    tail -10 "$LOG_FILE"
else
    echo "  (log file not found)"
fi
EOF
chmod +x "$LOCAL_BIN/label-studio-diagnostics"

# Ensure all commands are owned by the user
chown -R "$ACTUAL_USER:$ACTUAL_USER" "$LOCAL_BIN"

echo ""
echo "=============================================="
echo "✓ Label Studio installation complete!"
echo "  Installer version: ${SCRIPT_VERSION}"
echo "  Label Studio:      ${LS_VERSION}"
echo "=============================================="
echo ""
echo "All data is stored in: $LABEL_STUDIO_HOME"
echo "Commands are in:       $LOCAL_BIN (added to PATH)"
echo "Config file:          $LABEL_STUDIO_HOME/.env"
echo ""
echo "Available commands:"
echo "  label-studio-status       - Check if Label Studio is running"
echo "  label-studio-restart      - Restart Label Studio"
echo "  label-studio-stop         - Stop Label Studio"
echo "  label-studio-logs         - View Label Studio logs"
echo "  label-studio-update       - Update Label Studio to latest version"
echo "  label-studio-set-url URL  - Set your Cloud Workstation external URL"
echo "  label-studio-diagnostics  - Show config, detected URL, and connection info"
echo ""
echo "IMPORTANT — If you see a CSRF/403 error on login:"
echo "  The startup script auto-detects your workstation URL via DNS."
echo "  If it fails, set it manually after Label Studio starts:"
echo ""
echo "    label-studio-set-url https://8080-\$(hostname).YOUR-CLUSTER.cloudworkstations.dev"
echo ""
echo "  Run 'label-studio-diagnostics' to see what URL was detected."
echo ""
echo "NOTE: Commands persist across workstation restarts (stored in ~/.local/bin)."
echo "      To use commands in this terminal session, run: source ~/.bashrc"
echo ""
echo "Starting Label Studio now..."
"$LABEL_STUDIO_HOME/startup.sh"
echo ""
echo "Waiting for Label Studio to initialize..."
echo "Note: First run may take 2-3 minutes while the database is set up."
echo ""

# Wait for Label Studio to be ready (first run needs longer due to DB migrations)
MAX_WAIT=180
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null)
    if echo "$HTTP_CODE" | grep -q "200\|302"; then
        echo ""
        echo "✓ Label Studio is ready! ($WAITED seconds)"
        echo ""
        echo "Access Label Studio at: http://localhost:8080"
        echo "For Cloud Workstations, use your workstation's port 8080 URL."
        exit 0
    fi
    sleep 10
    WAITED=$((WAITED + 10))
    # Show log tail every 30 seconds to help debug
    if [ $((WAITED % 30)) -eq 0 ]; then
        LOG_FILE="$LABEL_STUDIO_HOME/label-studio.log"
        if [ -f "$LOG_FILE" ]; then
            echo "  --- Recent log output ---"
            tail -3 "$LOG_FILE"
            echo "  -------------------------"
        fi
    fi
    echo "  Still waiting... ($WAITED seconds)"
done

echo ""
echo "Label Studio is taking longer than expected to start."
echo ""
echo "Check the process:  ps aux | grep label-studio"
echo "Check status:       label-studio-status"
echo "Check logs:         label-studio-logs"
echo ""
echo "Once ready, access at: http://localhost:8080"
