#!/bin/bash
# =============================================================================
# JupyterLab Setup for Google Cloud Workstations
# Version: 1.0.1 (2026-03-25)
# =============================================================================
# Installs JupyterLab in a persistent location (~/.jupyter-env) with useful
# extensions. Auto-starts on workstation boot via .bashrc fallback.
#
# Access via Cloud Workstation port forwarding on port 8888.
#
# Usage:
#   bash setup_jupyter.sh
# =============================================================================

SCRIPT_VERSION="1.0.1"

echo "=============================================="
echo "JupyterLab Setup v${SCRIPT_VERSION}"
echo "=============================================="
echo ""

# Detect the actual user
ACTUAL_USER="${SUDO_USER:-$USER}"
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)

echo "User: $ACTUAL_USER"
echo "Home: $ACTUAL_HOME"
echo ""

JUPYTER_HOME="$ACTUAL_HOME/.jupyter-env"
JUPYTER_CONFIG="$ACTUAL_HOME/.jupyter"
LOCAL_BIN="$ACTUAL_HOME/.local/bin"

# ============================================================
# STEP 1: Check Python
# ============================================================
echo "[Step 1/6] Checking Python..."

# Try to find Python 3.10+
PYTHON_CMD=""
for py in python3.12 python3.11 python3.10 python3; do
    if command -v "$py" &>/dev/null; then
        PY_VERSION=$("$py" --version 2>&1 | grep -oE '[0-9]+\.[0-9]+' | head -1)
        PY_MAJOR=$(echo "$PY_VERSION" | cut -d. -f1)
        PY_MINOR=$(echo "$PY_VERSION" | cut -d. -f2)
        if [ "$PY_MAJOR" -ge 3 ] && [ "$PY_MINOR" -ge 10 ]; then
            PYTHON_CMD="$py"
            break
        fi
    fi
done

if [ -z "$PYTHON_CMD" ]; then
    echo "Python 3.10+ not found. Installing Python 3.12..."
    sudo apt-get update -qq
    sudo apt-get install -y -qq python3.12 python3.12-venv python3.12-dev
    PYTHON_CMD="python3.12"
fi

echo "Using: $PYTHON_CMD ($($PYTHON_CMD --version))"

# ============================================================
# STEP 2: Create virtual environment
# ============================================================
echo "[Step 2/6] Creating JupyterLab environment..."

if [ -d "$JUPYTER_HOME" ]; then
    echo "Environment exists at $JUPYTER_HOME"
else
    sudo -u "$ACTUAL_USER" "$PYTHON_CMD" -m venv "$JUPYTER_HOME"
fi

# Upgrade pip
sudo -u "$ACTUAL_USER" "$JUPYTER_HOME/bin/pip" install --upgrade pip -q

# ============================================================
# STEP 3: Install JupyterLab and extensions
# ============================================================
echo "[Step 3/6] Installing JupyterLab and extensions..."

sudo -u "$ACTUAL_USER" "$JUPYTER_HOME/bin/pip" install -q \
    jupyterlab \
    jupyterlab-git \
    jupyterlab-lsp \
    python-lsp-server[all] \
    ipywidgets \
    nbconvert \
    pandas \
    numpy \
    matplotlib \
    seaborn \
    plotly

echo "Installed JupyterLab $($JUPYTER_HOME/bin/jupyter --version 2>/dev/null | head -1)"

# ============================================================
# STEP 4: Configure JupyterLab
# ============================================================
echo "[Step 4/6] Configuring JupyterLab..."

sudo -u "$ACTUAL_USER" mkdir -p "$JUPYTER_CONFIG"

# Generate config with secure defaults
sudo -u "$ACTUAL_USER" bash -c "cat > '$JUPYTER_CONFIG/jupyter_lab_config.py'" << 'EOF'
# JupyterLab configuration for Cloud Workstations
# Generated by setup_jupyter.sh

c = get_config()

# Network settings
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.port = 8888
c.ServerApp.open_browser = False
c.ServerApp.allow_remote_access = True

# Disable token/password for Cloud Workstation (IAM handles auth)
c.ServerApp.token = ''
c.ServerApp.password = ''

# Trust notebooks by default (for Cloud Workstation use)
c.ServerApp.trust_xsrf = True

# Allow iframe embedding (for Cloud Workstation port forwarding)
c.ServerApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'self' https://*.cloudworkstations.dev"
    }
}

# Notebook directory
c.ServerApp.root_dir = '/home/user'

# Disable shutdown button (managed by startup script)
c.ServerApp.shutdown_no_activity_timeout = 0
EOF

# ============================================================
# STEP 5: Create management commands
# ============================================================
echo "[Step 5/6] Creating management commands..."

sudo -u "$ACTUAL_USER" mkdir -p "$LOCAL_BIN"

# jupyter-start
sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/jupyter-start'" << 'EOF'
#!/bin/bash
JUPYTER_HOME="$HOME/.jupyter-env"
LOG_FILE="$HOME/.jupyter/jupyter.log"

if pgrep -f "jupyter-lab" > /dev/null; then
    echo "JupyterLab is already running."
    echo "Access at: http://localhost:8888"
    exit 0
fi

echo "Starting JupyterLab..."
mkdir -p "$(dirname $LOG_FILE)"
nohup "$JUPYTER_HOME/bin/jupyter" lab >> "$LOG_FILE" 2>&1 &
echo $! > "$HOME/.jupyter/jupyter.pid"

sleep 3
if pgrep -f "jupyter-lab" > /dev/null; then
    echo "✓ JupyterLab started"
    echo "  Access at: http://localhost:8888"
    echo "  Logs: $LOG_FILE"
else
    echo "✗ Failed to start JupyterLab"
    echo "  Check logs: $LOG_FILE"
fi
EOF
chmod +x "$LOCAL_BIN/jupyter-start"

# jupyter-stop
sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/jupyter-stop'" << 'EOF'
#!/bin/bash
if pgrep -f "jupyter-lab" > /dev/null; then
    echo "Stopping JupyterLab..."
    pkill -f "jupyter-lab"
    echo "✓ JupyterLab stopped."
else
    echo "JupyterLab is not running."
fi
EOF
chmod +x "$LOCAL_BIN/jupyter-stop"

# jupyter-restart
sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/jupyter-restart'" << 'EOF'
#!/bin/bash
echo "Restarting JupyterLab..."
pkill -f "jupyter-lab" 2>/dev/null || true
sleep 1
"$HOME/.local/bin/jupyter-start"
EOF
chmod +x "$LOCAL_BIN/jupyter-restart"

# jupyter-status
sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/jupyter-status'" << 'EOF'
#!/bin/bash
JUPYTER_HOME="$HOME/.jupyter-env"

if pgrep -f "jupyter-lab" > /dev/null; then
    VERSION=$("$JUPYTER_HOME/bin/jupyter" --version 2>/dev/null | grep jupyterlab | awk '{print $NF}')
    echo "✓ JupyterLab is running"
    echo "  PID:     $(pgrep -f 'jupyter-lab')"
    echo "  Version: $VERSION"
    echo "  URL:     http://localhost:8888"
    echo "  Logs:    $HOME/.jupyter/jupyter.log"
else
    echo "✗ JupyterLab is not running"
    echo "  Start with: jupyter-start"
fi
EOF
chmod +x "$LOCAL_BIN/jupyter-status"

# jupyter-logs
sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/jupyter-logs'" << 'EOF'
#!/bin/bash
LOG_FILE="$HOME/.jupyter/jupyter.log"
if [ -f "$LOG_FILE" ]; then
    tail -f "$LOG_FILE"
else
    echo "No log file found at $LOG_FILE"
fi
EOF
chmod +x "$LOCAL_BIN/jupyter-logs"

# ============================================================
# STEP 6: Add to PATH and autostart
# ============================================================
echo "[Step 6/6] Setting up persistence..."

BASHRC="$ACTUAL_HOME/.bashrc"

# Add to PATH if not present
if ! grep -q 'export PATH=.*\.local/bin' "$BASHRC" 2>/dev/null; then
    sudo -u "$ACTUAL_USER" bash -c "echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> '$BASHRC'"
fi

# Add autostart (optional - commented out by default)
if ! grep -q 'jupyter-autostart' "$BASHRC" 2>/dev/null; then
    sudo -u "$ACTUAL_USER" bash -c "cat >> '$BASHRC'" << 'EOF'

# JupyterLab auto-start (uncomment to enable)
# if [ -f "$HOME/.jupyter-env/bin/jupyter" ] && ! pgrep -f "jupyter-lab" > /dev/null 2>&1; then
#     echo "Starting JupyterLab in background..."
#     nohup "$HOME/.jupyter-env/bin/jupyter" lab >> "$HOME/.jupyter/jupyter.log" 2>&1 &
# fi
# jupyter-autostart marker
EOF
fi

# ============================================================
# Start JupyterLab now
# ============================================================
echo ""
echo "Starting JupyterLab..."
"$LOCAL_BIN/jupyter-start"

echo ""
echo "=============================================="
echo "✓ JupyterLab Setup Complete!"
echo "=============================================="
echo ""
echo "Access at: http://localhost:8888"
echo "(Use Cloud Workstation port forwarding for external access)"
echo ""
echo "Commands (run 'source ~/.bashrc' first):"
echo "  jupyter-start   - Start JupyterLab"
echo "  jupyter-stop    - Stop JupyterLab"
echo "  jupyter-restart - Restart JupyterLab"
echo "  jupyter-status  - Check status"
echo "  jupyter-logs    - View logs"
echo ""
echo "To enable auto-start on workstation boot:"
echo "  Edit ~/.bashrc and uncomment the JupyterLab auto-start section"
echo ""
